### ISSUE TITLE
Misleading comment

### ISSUE THREAD

**Issue by maeb** [nlnwa/gowarc#70]
The following comment:
https://github.com/nlnwa/gowarc/blob/614c93db283029742004f3d6147620f2f6bbf846/warcfile.go#L526
seems to be inaccurate because
https://github.com/nlnwa/gowarc/blob/614c93db283029742004f3d6147620f2f6bbf846/warcfile.go#L540
leads to
https://github.com/nlnwa/gowarc/blob/614c93db283029742004f3d6147620f2f6bbf846/unmarshaler.go#L196-L202
which returns a warcRecord which is not nil on error.

**Comment by johnerikhalse** [comment]
This will be fixed in PR #69
